version: "3"
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./my-app/:/home/node/app
    command: >
      sh -c "NODE_ENV=development npm install &&
             npm run build && node ./build/index.js"
    ports:
      - 3001:3001
